### ISSUE TITLE
Surface on load callback not firing when texture url changes

### ISSUE THREAD

**Issue by Maxoos** [ProjectSeptemberInc/gl-react#38]
Hey,

I am changing the texture url via props, while everything works fine the callbacks do not fire. Both onLoad and onProgress only fire on initial load. I was going to use that callback to show a loading indicator when loading a new texture. Is that something you can fix or maybe there is a way to go around it?

Thanks!

**Comment by gre** [comment]
one workaround for your use-case is to change the `key` of your surface to force React to recreate a new GL.Surface.


onLoad and onProgress of gl-react are only triggered once.
This is a way to track the fact that (if you use preload) the GL.Surface won't render until textures are ready (there are two states: "notReady" initial state and "ready" final state). but when images are loaded, and if you load new once, the GL.Surface won't prevent the rendering anymore to avoid "blink" you could get.

**Comment by Maxoos** [comment]
Thanks! Yes it does blink. Can you think of any other way to trigger the progress indicator?

**Comment by gre** [comment]
I guess you are right that onLoad should be triggered again if new textures has been loaded after onLoad was already triggered. I probably need to trigger an event to indicate that loading is in progress (I guess onLoadStart like on HTML5 Media events).

I guess the rendering would stuck during that phase **if you enable preload** feature.


This is a change in the semantic so it will need to wait for at least a minor release.

**Comment by Maxoos** [comment]
Awesome. I have a related question though. Even though the onLoad is only firing once when loaded, and there is no key on Surface, when I switch texture images via props I still see a blink. This should not happen should it?

**Comment by gre** [comment]
there is no "onLoadStart" event yet,
but I should have fixed the 2 bug mentioned (blink and onLoad to re-trigger) in `gl-react-dom` implementation (v2.0.9), I should fix this in gl-react-native soon.

(for instance, [this example](http://projectseptemberinc.github.io/gl-react-dom/Examples/Blur/) used to blink when changing the textures)

**Comment by gre** [comment]
also released `gl-react-native 2.17.1` for this.

Please confirm if the bug is fixed for you.

**Comment by Maxoos** [comment]
Hey, thanks for handling this. 

Well this is interesting, updated `gl-react-dom` from 2.0.3 to 2.0.10 and now the events do fire up. Did you change anything?
 
Blinks are still there, in fact you can still see them in the example you've linked, it's just harder to see. Switch between the first blur and the second blur quickly and you'll see that sometimes the unprocessed image appears briefly.

Thanks!

**Comment by gre** [comment]
Yeah onLoad is fixed.
I guess I've fixed half of the problem for the blink issue. I'll give another try and investigate where it happens

**Comment by gre** [comment]
@Maxoos I've released a v2.0.11 where the blink issue should be fixed.

The bug should no longer appear on that example.

**Comment by Maxoos** [comment]
@gre Well done! works great, thanks!

**Comment by gre** [comment]
cool thanks
